'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SysproQueryService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.syspro.com/ns/query/", ConfigurationName:="SysproQueryService.queryclassSoap")>  _
    Public Interface queryclassSoap
        
        'CODEGEN: Generating message contract since the wrapper name (Browse_With_String) of message Browse_With_String does not match the default value (Browse)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/Browse_With_String", ReplyAction:="*")>  _
        Function Browse(ByVal request As SysproQueryService.Browse_With_String) As SysproQueryService.Browse_With_String1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/Browse_With_String", ReplyAction:="*")>  _
        Function BrowseAsync(ByVal request As SysproQueryService.Browse_With_String) As System.Threading.Tasks.Task(Of SysproQueryService.Browse_With_String1)
        
        'CODEGEN: Generating message contract since the wrapper name (Browse_With_ByteArray) of message Browse_With_ByteArray does not match the default value (BrowseW)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/Browse_With_ByteArray", ReplyAction:="*")>  _
        Function BrowseW(ByVal request As SysproQueryService.Browse_With_ByteArray) As SysproQueryService.Browse_With_ByteArray1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/Browse_With_ByteArray", ReplyAction:="*")>  _
        Function BrowseWAsync(ByVal request As SysproQueryService.Browse_With_ByteArray) As System.Threading.Tasks.Task(Of SysproQueryService.Browse_With_ByteArray1)
        
        'CODEGEN: Generating message contract since the wrapper name (Fetch_With_String) of message Fetch_With_String does not match the default value (Fetch)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/Fetch_With_String", ReplyAction:="*")>  _
        Function Fetch(ByVal request As SysproQueryService.Fetch_With_String) As SysproQueryService.Fetch_With_String1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/Fetch_With_String", ReplyAction:="*")>  _
        Function FetchAsync(ByVal request As SysproQueryService.Fetch_With_String) As System.Threading.Tasks.Task(Of SysproQueryService.Fetch_With_String1)
        
        'CODEGEN: Generating message contract since the wrapper name (Fetch_With_ByteArray) of message Fetch_With_ByteArray does not match the default value (FetchW)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/Fetch_With_ByteArray", ReplyAction:="*")>  _
        Function FetchW(ByVal request As SysproQueryService.Fetch_With_ByteArray) As SysproQueryService.Fetch_With_ByteArray1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/Fetch_With_ByteArray", ReplyAction:="*")>  _
        Function FetchWAsync(ByVal request As SysproQueryService.Fetch_With_ByteArray) As System.Threading.Tasks.Task(Of SysproQueryService.Fetch_With_ByteArray1)
        
        'CODEGEN: Generating message contract since the wrapper name (Query_With_String) of message Query_With_String does not match the default value (Query)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/Query_With_String", ReplyAction:="*")>  _
        Function Query(ByVal request As SysproQueryService.Query_With_String) As SysproQueryService.Query_With_String1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/Query_With_String", ReplyAction:="*")>  _
        Function QueryAsync(ByVal request As SysproQueryService.Query_With_String) As System.Threading.Tasks.Task(Of SysproQueryService.Query_With_String1)
        
        'CODEGEN: Generating message contract since the wrapper name (Query_With_ByteArray) of message Query_With_ByteArray does not match the default value (QueryW)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/Query_With_ByteArray", ReplyAction:="*")>  _
        Function QueryW(ByVal request As SysproQueryService.Query_With_ByteArray) As SysproQueryService.Query_With_ByteArray1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/Query_With_ByteArray", ReplyAction:="*")>  _
        Function QueryWAsync(ByVal request As SysproQueryService.Query_With_ByteArray) As System.Threading.Tasks.Task(Of SysproQueryService.Query_With_ByteArray1)
        
        'CODEGEN: Generating message contract since the wrapper name (NextKey_With_String) of message NextKey_With_String does not match the default value (NextKey)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/NextKey_With_String", ReplyAction:="*")>  _
        Function NextKey(ByVal request As SysproQueryService.NextKey_With_String) As SysproQueryService.NextKey_With_String1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/NextKey_With_String", ReplyAction:="*")>  _
        Function NextKeyAsync(ByVal request As SysproQueryService.NextKey_With_String) As System.Threading.Tasks.Task(Of SysproQueryService.NextKey_With_String1)
        
        'CODEGEN: Generating message contract since the wrapper name (NextKey_With_ByteArray) of message NextKey_With_ByteArray does not match the default value (NextKeyW)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/NextKey_With_ByteArray", ReplyAction:="*")>  _
        Function NextKeyW(ByVal request As SysproQueryService.NextKey_With_ByteArray) As SysproQueryService.NextKey_With_ByteArray1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/NextKey_With_ByteArray", ReplyAction:="*")>  _
        Function NextKeyWAsync(ByVal request As SysproQueryService.NextKey_With_ByteArray) As System.Threading.Tasks.Task(Of SysproQueryService.NextKey_With_ByteArray1)
        
        'CODEGEN: Generating message contract since the wrapper name (PreviousKey_With_String) of message PreviousKey_With_String does not match the default value (PreviousKey)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/PreviousKey_With_String", ReplyAction:="*")>  _
        Function PreviousKey(ByVal request As SysproQueryService.PreviousKey_With_String) As SysproQueryService.PreviousKey_With_String1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/PreviousKey_With_String", ReplyAction:="*")>  _
        Function PreviousKeyAsync(ByVal request As SysproQueryService.PreviousKey_With_String) As System.Threading.Tasks.Task(Of SysproQueryService.PreviousKey_With_String1)
        
        'CODEGEN: Generating message contract since the wrapper name (PreviousKey_With_ByteArray) of message PreviousKey_With_ByteArray does not match the default value (PreviousKeyW)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/PreviousKey_With_ByteArray", ReplyAction:="*")>  _
        Function PreviousKeyW(ByVal request As SysproQueryService.PreviousKey_With_ByteArray) As SysproQueryService.PreviousKey_With_ByteArray1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/query/PreviousKey_With_ByteArray", ReplyAction:="*")>  _
        Function PreviousKeyWAsync(ByVal request As SysproQueryService.PreviousKey_With_ByteArray) As System.Threading.Tasks.Task(Of SysproQueryService.PreviousKey_With_ByteArray1)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Browse_With_String", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class Browse_With_String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public UserId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=1)>  _
        Public XMLIn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String, ByVal XMLIn As String)
            MyBase.New
            Me.UserId = UserId
            Me.XMLIn = XMLIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Browse_With_StringResponse", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class Browse_With_String1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public Browse_With_StringResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Browse_With_StringResult As String)
            MyBase.New
            Me.Browse_With_StringResult = Browse_With_StringResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Browse_With_ByteArray", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class Browse_With_ByteArray
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public UserId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=1)>  _
        Public XMLIn() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String, ByVal XMLIn() As Byte)
            MyBase.New
            Me.UserId = UserId
            Me.XMLIn = XMLIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Browse_With_ByteArrayResponse", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class Browse_With_ByteArray1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public Browse_With_ByteArrayResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Browse_With_ByteArrayResult() As Byte)
            MyBase.New
            Me.Browse_With_ByteArrayResult = Browse_With_ByteArrayResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Fetch_With_String", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class Fetch_With_String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public UserId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=1)>  _
        Public XMLIn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String, ByVal XMLIn As String)
            MyBase.New
            Me.UserId = UserId
            Me.XMLIn = XMLIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Fetch_With_StringResponse", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class Fetch_With_String1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public Fetch_With_StringResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Fetch_With_StringResult As String)
            MyBase.New
            Me.Fetch_With_StringResult = Fetch_With_StringResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Fetch_With_ByteArray", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class Fetch_With_ByteArray
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public UserId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=1)>  _
        Public XMLIn() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String, ByVal XMLIn() As Byte)
            MyBase.New
            Me.UserId = UserId
            Me.XMLIn = XMLIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Fetch_With_ByteArrayResponse", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class Fetch_With_ByteArray1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public Fetch_With_ByteArrayResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Fetch_With_ByteArrayResult() As Byte)
            MyBase.New
            Me.Fetch_With_ByteArrayResult = Fetch_With_ByteArrayResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Query_With_String", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class Query_With_String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public UserId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=1)>  _
        Public BusinessObject As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=2)>  _
        Public XMLIn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String, ByVal BusinessObject As String, ByVal XMLIn As String)
            MyBase.New
            Me.UserId = UserId
            Me.BusinessObject = BusinessObject
            Me.XMLIn = XMLIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Query_With_StringResponse", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class Query_With_String1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public Query_With_StringResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Query_With_StringResult As String)
            MyBase.New
            Me.Query_With_StringResult = Query_With_StringResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Query_With_ByteArray", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class Query_With_ByteArray
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public UserId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=1)>  _
        Public BusinessObject As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=2)>  _
        Public XMLIn() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String, ByVal BusinessObject As String, ByVal XMLIn() As Byte)
            MyBase.New
            Me.UserId = UserId
            Me.BusinessObject = BusinessObject
            Me.XMLIn = XMLIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Query_With_ByteArrayResponse", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class Query_With_ByteArray1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public Query_With_ByteArrayResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Query_With_ByteArrayResult() As Byte)
            MyBase.New
            Me.Query_With_ByteArrayResult = Query_With_ByteArrayResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="NextKey_With_String", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class NextKey_With_String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public UserId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=1)>  _
        Public XMLIn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String, ByVal XMLIn As String)
            MyBase.New
            Me.UserId = UserId
            Me.XMLIn = XMLIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="NextKey_With_StringResponse", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class NextKey_With_String1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public NextKey_With_StringResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal NextKey_With_StringResult As String)
            MyBase.New
            Me.NextKey_With_StringResult = NextKey_With_StringResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="NextKey_With_ByteArray", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class NextKey_With_ByteArray
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public UserId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=1)>  _
        Public XMLIn() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String, ByVal XMLIn() As Byte)
            MyBase.New
            Me.UserId = UserId
            Me.XMLIn = XMLIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="NextKey_With_ByteArrayResponse", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class NextKey_With_ByteArray1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public NextKey_With_ByteArrayResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal NextKey_With_ByteArrayResult() As Byte)
            MyBase.New
            Me.NextKey_With_ByteArrayResult = NextKey_With_ByteArrayResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="PreviousKey_With_String", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class PreviousKey_With_String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public UserId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=1)>  _
        Public XMLIn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String, ByVal XMLIn As String)
            MyBase.New
            Me.UserId = UserId
            Me.XMLIn = XMLIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="PreviousKey_With_StringResponse", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class PreviousKey_With_String1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public PreviousKey_With_StringResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PreviousKey_With_StringResult As String)
            MyBase.New
            Me.PreviousKey_With_StringResult = PreviousKey_With_StringResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="PreviousKey_With_ByteArray", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class PreviousKey_With_ByteArray
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public UserId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=1)>  _
        Public XMLIn() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String, ByVal XMLIn() As Byte)
            MyBase.New
            Me.UserId = UserId
            Me.XMLIn = XMLIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="PreviousKey_With_ByteArrayResponse", WrapperNamespace:="http://www.syspro.com/ns/query/", IsWrapped:=true)>  _
    Partial Public Class PreviousKey_With_ByteArray1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/query/", Order:=0)>  _
        Public PreviousKey_With_ByteArrayResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PreviousKey_With_ByteArrayResult() As Byte)
            MyBase.New
            Me.PreviousKey_With_ByteArrayResult = PreviousKey_With_ByteArrayResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface queryclassSoapChannel
        Inherits SysproQueryService.queryclassSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class queryclassSoapClient
        Inherits System.ServiceModel.ClientBase(Of SysproQueryService.queryclassSoap)
        Implements SysproQueryService.queryclassSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_Browse(ByVal request As SysproQueryService.Browse_With_String) As SysproQueryService.Browse_With_String1 Implements SysproQueryService.queryclassSoap.Browse
            Return MyBase.Channel.Browse(request)
        End Function
        
        Public Function Browse(ByVal UserId As String, ByVal XMLIn As String) As String
            Dim inValue As SysproQueryService.Browse_With_String = New SysproQueryService.Browse_With_String()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Dim retVal As SysproQueryService.Browse_With_String1 = CType(Me,SysproQueryService.queryclassSoap).Browse(inValue)
            Return retVal.Browse_With_StringResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_BrowseAsync(ByVal request As SysproQueryService.Browse_With_String) As System.Threading.Tasks.Task(Of SysproQueryService.Browse_With_String1) Implements SysproQueryService.queryclassSoap.BrowseAsync
            Return MyBase.Channel.BrowseAsync(request)
        End Function
        
        Public Function BrowseAsync(ByVal UserId As String, ByVal XMLIn As String) As System.Threading.Tasks.Task(Of SysproQueryService.Browse_With_String1)
            Dim inValue As SysproQueryService.Browse_With_String = New SysproQueryService.Browse_With_String()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Return CType(Me,SysproQueryService.queryclassSoap).BrowseAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_BrowseW(ByVal request As SysproQueryService.Browse_With_ByteArray) As SysproQueryService.Browse_With_ByteArray1 Implements SysproQueryService.queryclassSoap.BrowseW
            Return MyBase.Channel.BrowseW(request)
        End Function
        
        Public Function BrowseW(ByVal UserId As String, ByVal XMLIn() As Byte) As Byte()
            Dim inValue As SysproQueryService.Browse_With_ByteArray = New SysproQueryService.Browse_With_ByteArray()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Dim retVal As SysproQueryService.Browse_With_ByteArray1 = CType(Me,SysproQueryService.queryclassSoap).BrowseW(inValue)
            Return retVal.Browse_With_ByteArrayResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_BrowseWAsync(ByVal request As SysproQueryService.Browse_With_ByteArray) As System.Threading.Tasks.Task(Of SysproQueryService.Browse_With_ByteArray1) Implements SysproQueryService.queryclassSoap.BrowseWAsync
            Return MyBase.Channel.BrowseWAsync(request)
        End Function
        
        Public Function BrowseWAsync(ByVal UserId As String, ByVal XMLIn() As Byte) As System.Threading.Tasks.Task(Of SysproQueryService.Browse_With_ByteArray1)
            Dim inValue As SysproQueryService.Browse_With_ByteArray = New SysproQueryService.Browse_With_ByteArray()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Return CType(Me,SysproQueryService.queryclassSoap).BrowseWAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_Fetch(ByVal request As SysproQueryService.Fetch_With_String) As SysproQueryService.Fetch_With_String1 Implements SysproQueryService.queryclassSoap.Fetch
            Return MyBase.Channel.Fetch(request)
        End Function
        
        Public Function Fetch(ByVal UserId As String, ByVal XMLIn As String) As String
            Dim inValue As SysproQueryService.Fetch_With_String = New SysproQueryService.Fetch_With_String()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Dim retVal As SysproQueryService.Fetch_With_String1 = CType(Me,SysproQueryService.queryclassSoap).Fetch(inValue)
            Return retVal.Fetch_With_StringResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_FetchAsync(ByVal request As SysproQueryService.Fetch_With_String) As System.Threading.Tasks.Task(Of SysproQueryService.Fetch_With_String1) Implements SysproQueryService.queryclassSoap.FetchAsync
            Return MyBase.Channel.FetchAsync(request)
        End Function
        
        Public Function FetchAsync(ByVal UserId As String, ByVal XMLIn As String) As System.Threading.Tasks.Task(Of SysproQueryService.Fetch_With_String1)
            Dim inValue As SysproQueryService.Fetch_With_String = New SysproQueryService.Fetch_With_String()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Return CType(Me,SysproQueryService.queryclassSoap).FetchAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_FetchW(ByVal request As SysproQueryService.Fetch_With_ByteArray) As SysproQueryService.Fetch_With_ByteArray1 Implements SysproQueryService.queryclassSoap.FetchW
            Return MyBase.Channel.FetchW(request)
        End Function
        
        Public Function FetchW(ByVal UserId As String, ByVal XMLIn() As Byte) As Byte()
            Dim inValue As SysproQueryService.Fetch_With_ByteArray = New SysproQueryService.Fetch_With_ByteArray()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Dim retVal As SysproQueryService.Fetch_With_ByteArray1 = CType(Me,SysproQueryService.queryclassSoap).FetchW(inValue)
            Return retVal.Fetch_With_ByteArrayResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_FetchWAsync(ByVal request As SysproQueryService.Fetch_With_ByteArray) As System.Threading.Tasks.Task(Of SysproQueryService.Fetch_With_ByteArray1) Implements SysproQueryService.queryclassSoap.FetchWAsync
            Return MyBase.Channel.FetchWAsync(request)
        End Function
        
        Public Function FetchWAsync(ByVal UserId As String, ByVal XMLIn() As Byte) As System.Threading.Tasks.Task(Of SysproQueryService.Fetch_With_ByteArray1)
            Dim inValue As SysproQueryService.Fetch_With_ByteArray = New SysproQueryService.Fetch_With_ByteArray()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Return CType(Me,SysproQueryService.queryclassSoap).FetchWAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_Query(ByVal request As SysproQueryService.Query_With_String) As SysproQueryService.Query_With_String1 Implements SysproQueryService.queryclassSoap.Query
            Return MyBase.Channel.Query(request)
        End Function
        
        Public Function Query(ByVal UserId As String, ByVal BusinessObject As String, ByVal XMLIn As String) As String
            Dim inValue As SysproQueryService.Query_With_String = New SysproQueryService.Query_With_String()
            inValue.UserId = UserId
            inValue.BusinessObject = BusinessObject
            inValue.XMLIn = XMLIn
            Dim retVal As SysproQueryService.Query_With_String1 = CType(Me,SysproQueryService.queryclassSoap).Query(inValue)
            Return retVal.Query_With_StringResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_QueryAsync(ByVal request As SysproQueryService.Query_With_String) As System.Threading.Tasks.Task(Of SysproQueryService.Query_With_String1) Implements SysproQueryService.queryclassSoap.QueryAsync
            Return MyBase.Channel.QueryAsync(request)
        End Function
        
        Public Function QueryAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XMLIn As String) As System.Threading.Tasks.Task(Of SysproQueryService.Query_With_String1)
            Dim inValue As SysproQueryService.Query_With_String = New SysproQueryService.Query_With_String()
            inValue.UserId = UserId
            inValue.BusinessObject = BusinessObject
            inValue.XMLIn = XMLIn
            Return CType(Me,SysproQueryService.queryclassSoap).QueryAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_QueryW(ByVal request As SysproQueryService.Query_With_ByteArray) As SysproQueryService.Query_With_ByteArray1 Implements SysproQueryService.queryclassSoap.QueryW
            Return MyBase.Channel.QueryW(request)
        End Function
        
        Public Function QueryW(ByVal UserId As String, ByVal BusinessObject As String, ByVal XMLIn() As Byte) As Byte()
            Dim inValue As SysproQueryService.Query_With_ByteArray = New SysproQueryService.Query_With_ByteArray()
            inValue.UserId = UserId
            inValue.BusinessObject = BusinessObject
            inValue.XMLIn = XMLIn
            Dim retVal As SysproQueryService.Query_With_ByteArray1 = CType(Me,SysproQueryService.queryclassSoap).QueryW(inValue)
            Return retVal.Query_With_ByteArrayResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_QueryWAsync(ByVal request As SysproQueryService.Query_With_ByteArray) As System.Threading.Tasks.Task(Of SysproQueryService.Query_With_ByteArray1) Implements SysproQueryService.queryclassSoap.QueryWAsync
            Return MyBase.Channel.QueryWAsync(request)
        End Function
        
        Public Function QueryWAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal XMLIn() As Byte) As System.Threading.Tasks.Task(Of SysproQueryService.Query_With_ByteArray1)
            Dim inValue As SysproQueryService.Query_With_ByteArray = New SysproQueryService.Query_With_ByteArray()
            inValue.UserId = UserId
            inValue.BusinessObject = BusinessObject
            inValue.XMLIn = XMLIn
            Return CType(Me,SysproQueryService.queryclassSoap).QueryWAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_NextKey(ByVal request As SysproQueryService.NextKey_With_String) As SysproQueryService.NextKey_With_String1 Implements SysproQueryService.queryclassSoap.NextKey
            Return MyBase.Channel.NextKey(request)
        End Function
        
        Public Function NextKey(ByVal UserId As String, ByVal XMLIn As String) As String
            Dim inValue As SysproQueryService.NextKey_With_String = New SysproQueryService.NextKey_With_String()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Dim retVal As SysproQueryService.NextKey_With_String1 = CType(Me,SysproQueryService.queryclassSoap).NextKey(inValue)
            Return retVal.NextKey_With_StringResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_NextKeyAsync(ByVal request As SysproQueryService.NextKey_With_String) As System.Threading.Tasks.Task(Of SysproQueryService.NextKey_With_String1) Implements SysproQueryService.queryclassSoap.NextKeyAsync
            Return MyBase.Channel.NextKeyAsync(request)
        End Function
        
        Public Function NextKeyAsync(ByVal UserId As String, ByVal XMLIn As String) As System.Threading.Tasks.Task(Of SysproQueryService.NextKey_With_String1)
            Dim inValue As SysproQueryService.NextKey_With_String = New SysproQueryService.NextKey_With_String()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Return CType(Me,SysproQueryService.queryclassSoap).NextKeyAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_NextKeyW(ByVal request As SysproQueryService.NextKey_With_ByteArray) As SysproQueryService.NextKey_With_ByteArray1 Implements SysproQueryService.queryclassSoap.NextKeyW
            Return MyBase.Channel.NextKeyW(request)
        End Function
        
        Public Function NextKeyW(ByVal UserId As String, ByVal XMLIn() As Byte) As Byte()
            Dim inValue As SysproQueryService.NextKey_With_ByteArray = New SysproQueryService.NextKey_With_ByteArray()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Dim retVal As SysproQueryService.NextKey_With_ByteArray1 = CType(Me,SysproQueryService.queryclassSoap).NextKeyW(inValue)
            Return retVal.NextKey_With_ByteArrayResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_NextKeyWAsync(ByVal request As SysproQueryService.NextKey_With_ByteArray) As System.Threading.Tasks.Task(Of SysproQueryService.NextKey_With_ByteArray1) Implements SysproQueryService.queryclassSoap.NextKeyWAsync
            Return MyBase.Channel.NextKeyWAsync(request)
        End Function
        
        Public Function NextKeyWAsync(ByVal UserId As String, ByVal XMLIn() As Byte) As System.Threading.Tasks.Task(Of SysproQueryService.NextKey_With_ByteArray1)
            Dim inValue As SysproQueryService.NextKey_With_ByteArray = New SysproQueryService.NextKey_With_ByteArray()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Return CType(Me,SysproQueryService.queryclassSoap).NextKeyWAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_PreviousKey(ByVal request As SysproQueryService.PreviousKey_With_String) As SysproQueryService.PreviousKey_With_String1 Implements SysproQueryService.queryclassSoap.PreviousKey
            Return MyBase.Channel.PreviousKey(request)
        End Function
        
        Public Function PreviousKey(ByVal UserId As String, ByVal XMLIn As String) As String
            Dim inValue As SysproQueryService.PreviousKey_With_String = New SysproQueryService.PreviousKey_With_String()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Dim retVal As SysproQueryService.PreviousKey_With_String1 = CType(Me,SysproQueryService.queryclassSoap).PreviousKey(inValue)
            Return retVal.PreviousKey_With_StringResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_PreviousKeyAsync(ByVal request As SysproQueryService.PreviousKey_With_String) As System.Threading.Tasks.Task(Of SysproQueryService.PreviousKey_With_String1) Implements SysproQueryService.queryclassSoap.PreviousKeyAsync
            Return MyBase.Channel.PreviousKeyAsync(request)
        End Function
        
        Public Function PreviousKeyAsync(ByVal UserId As String, ByVal XMLIn As String) As System.Threading.Tasks.Task(Of SysproQueryService.PreviousKey_With_String1)
            Dim inValue As SysproQueryService.PreviousKey_With_String = New SysproQueryService.PreviousKey_With_String()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Return CType(Me,SysproQueryService.queryclassSoap).PreviousKeyAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_PreviousKeyW(ByVal request As SysproQueryService.PreviousKey_With_ByteArray) As SysproQueryService.PreviousKey_With_ByteArray1 Implements SysproQueryService.queryclassSoap.PreviousKeyW
            Return MyBase.Channel.PreviousKeyW(request)
        End Function
        
        Public Function PreviousKeyW(ByVal UserId As String, ByVal XMLIn() As Byte) As Byte()
            Dim inValue As SysproQueryService.PreviousKey_With_ByteArray = New SysproQueryService.PreviousKey_With_ByteArray()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Dim retVal As SysproQueryService.PreviousKey_With_ByteArray1 = CType(Me,SysproQueryService.queryclassSoap).PreviousKeyW(inValue)
            Return retVal.PreviousKey_With_ByteArrayResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproQueryService_queryclassSoap_PreviousKeyWAsync(ByVal request As SysproQueryService.PreviousKey_With_ByteArray) As System.Threading.Tasks.Task(Of SysproQueryService.PreviousKey_With_ByteArray1) Implements SysproQueryService.queryclassSoap.PreviousKeyWAsync
            Return MyBase.Channel.PreviousKeyWAsync(request)
        End Function
        
        Public Function PreviousKeyWAsync(ByVal UserId As String, ByVal XMLIn() As Byte) As System.Threading.Tasks.Task(Of SysproQueryService.PreviousKey_With_ByteArray1)
            Dim inValue As SysproQueryService.PreviousKey_With_ByteArray = New SysproQueryService.PreviousKey_With_ByteArray()
            inValue.UserId = UserId
            inValue.XMLIn = XMLIn
            Return CType(Me,SysproQueryService.queryclassSoap).PreviousKeyWAsync(inValue)
        End Function
    End Class
End Namespace
