'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

Namespace SysproUtilitiesService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Language", [Namespace]:="http://www.syspro.com/ns/utilities/")>  _
    Public Enum Language As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [AUTO] = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ENGLISH_US = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        FRENCH_CANADIAN = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DANISH = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DUTCH = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ENGLISH = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        FINNISH = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        FRENCH = 7
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        GERMAN = 8
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ITALIAN = 9
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NORWEGIAN = 10
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PORTUGUESE = 11
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SPANISH = 12
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SWEDISH = 13
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LogDetail", [Namespace]:="http://www.syspro.com/ns/utilities/")>  _
    Public Enum LogDetail As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ldNoDebug = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ldDebug = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Instance", [Namespace]:="http://www.syspro.com/ns/utilities/")>  _
    Public Enum Instance As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EncoreInstance_0 = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EncoreInstance_1 = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EncoreInstance_2 = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EncoreInstance_3 = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EncoreInstance_4 = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EncoreInstance_5 = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EncoreInstance_6 = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EncoreInstance_7 = 7
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EncoreInstance_8 = 8
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EncoreInstance_9 = 9
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EncoreInstanceTostring_10 = 10
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", ConfigurationName:="SysproUtilitiesService.utilitiesclassSoap")>  _
    Public Interface utilitiesclassSoap
        
        'CODEGEN: Generating message contract since the wrapper name (Logon_With_String) of message Logon_With_String does not match the default value (Logon)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/utilities/Logon_With_String", ReplyAction:="*")>  _
        Function Logon(ByVal request As SysproUtilitiesService.Logon_With_String) As SysproUtilitiesService.Logon_With_String1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/utilities/Logon_With_String", ReplyAction:="*")>  _
        Function LogonAsync(ByVal request As SysproUtilitiesService.Logon_With_String) As System.Threading.Tasks.Task(Of SysproUtilitiesService.Logon_With_String1)
        
        'CODEGEN: Generating message contract since the wrapper name (Logon_With_ByteArray) of message Logon_With_ByteArray does not match the default value (LogonW)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/utilities/Logon_With_ByteArray", ReplyAction:="*")>  _
        Function LogonW(ByVal request As SysproUtilitiesService.Logon_With_ByteArray) As SysproUtilitiesService.Logon_With_ByteArray1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/utilities/Logon_With_ByteArray", ReplyAction:="*")>  _
        Function LogonWAsync(ByVal request As SysproUtilitiesService.Logon_With_ByteArray) As System.Threading.Tasks.Task(Of SysproUtilitiesService.Logon_With_ByteArray1)
        
        'CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/utilities/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/utilities/Logoff", ReplyAction:="*")>  _
        Function Logoff(ByVal request As SysproUtilitiesService.LogoffRequest) As SysproUtilitiesService.LogoffResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/utilities/Logoff", ReplyAction:="*")>  _
        Function LogoffAsync(ByVal request As SysproUtilitiesService.LogoffRequest) As System.Threading.Tasks.Task(Of SysproUtilitiesService.LogoffResponse)
        
        'CODEGEN: Generating message contract since the wrapper name (GetLogonProfile_With_String) of message GetLogonProfile_With_String does not match the default value (GetLogonProfile)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/utilities/GetLogonProfile_With_String", ReplyAction:="*")>  _
        Function GetLogonProfile(ByVal request As SysproUtilitiesService.GetLogonProfile_With_String) As SysproUtilitiesService.GetLogonProfile_With_String1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/utilities/GetLogonProfile_With_String", ReplyAction:="*")>  _
        Function GetLogonProfileAsync(ByVal request As SysproUtilitiesService.GetLogonProfile_With_String) As System.Threading.Tasks.Task(Of SysproUtilitiesService.GetLogonProfile_With_String1)
        
        'CODEGEN: Generating message contract since the wrapper name (GetLogonProfile_With_ByteArray) of message GetLogonProfile_With_ByteArray does not match the default value (GetLogonProfileW)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/utilities/GetLogonProfile_With_ByteArray", ReplyAction:="*")>  _
        Function GetLogonProfileW(ByVal request As SysproUtilitiesService.GetLogonProfile_With_ByteArray) As SysproUtilitiesService.GetLogonProfile_With_ByteArray1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/utilities/GetLogonProfile_With_ByteArray", ReplyAction:="*")>  _
        Function GetLogonProfileWAsync(ByVal request As SysproUtilitiesService.GetLogonProfile_With_ByteArray) As System.Threading.Tasks.Task(Of SysproUtilitiesService.GetLogonProfile_With_ByteArray1)
        
        'CODEGEN: Generating message contract since the wrapper name (Run_With_String) of message Run_With_String does not match the default value (Run)
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/utilities/Run_With_String", ReplyAction:="*")>  _
        Function Run(ByVal request As SysproUtilitiesService.Run_With_String) As SysproUtilitiesService.Run_With_String1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.syspro.com/ns/utilities/Run_With_String", ReplyAction:="*")>  _
        Function RunAsync(ByVal request As SysproUtilitiesService.Run_With_String) As System.Threading.Tasks.Task(Of SysproUtilitiesService.Run_With_String1)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Logon_With_String", WrapperNamespace:="http://www.syspro.com/ns/utilities/", IsWrapped:=true)>  _
    Partial Public Class Logon_With_String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=0)>  _
        Public OperatorCode As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=1)>  _
        Public OperatorPassword As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=2)>  _
        Public CompanyId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=3)>  _
        Public CompanyPassword As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=4)>  _
        Public LanguageCode As SysproUtilitiesService.Language
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=5)>  _
        Public LogLevel As SysproUtilitiesService.LogDetail
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=6)>  _
        Public EncoreInstance As SysproUtilitiesService.Instance
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=7)>  _
        Public XmlIn As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal OperatorCode As String, ByVal OperatorPassword As String, ByVal CompanyId As String, ByVal CompanyPassword As String, ByVal LanguageCode As SysproUtilitiesService.Language, ByVal LogLevel As SysproUtilitiesService.LogDetail, ByVal EncoreInstance As SysproUtilitiesService.Instance, ByVal XmlIn As String)
            MyBase.New
            Me.OperatorCode = OperatorCode
            Me.OperatorPassword = OperatorPassword
            Me.CompanyId = CompanyId
            Me.CompanyPassword = CompanyPassword
            Me.LanguageCode = LanguageCode
            Me.LogLevel = LogLevel
            Me.EncoreInstance = EncoreInstance
            Me.XmlIn = XmlIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Logon_With_StringResponse", WrapperNamespace:="http://www.syspro.com/ns/utilities/", IsWrapped:=true)>  _
    Partial Public Class Logon_With_String1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=0)>  _
        Public Logon_With_StringResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Logon_With_StringResult As String)
            MyBase.New
            Me.Logon_With_StringResult = Logon_With_StringResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Logon_With_ByteArray", WrapperNamespace:="http://www.syspro.com/ns/utilities/", IsWrapped:=true)>  _
    Partial Public Class Logon_With_ByteArray
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=0)>  _
        Public OperatorCode As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=1)>  _
        Public OperatorPassword As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=2)>  _
        Public CompanyId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=3)>  _
        Public CompanyPassword As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=4)>  _
        Public LanguageCode As SysproUtilitiesService.Language
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=5)>  _
        Public LogLevel As SysproUtilitiesService.LogDetail
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=6)>  _
        Public EncoreInstance As SysproUtilitiesService.Instance
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=7)>  _
        Public XmlIn() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal OperatorCode As String, ByVal OperatorPassword As String, ByVal CompanyId As String, ByVal CompanyPassword As String, ByVal LanguageCode As SysproUtilitiesService.Language, ByVal LogLevel As SysproUtilitiesService.LogDetail, ByVal EncoreInstance As SysproUtilitiesService.Instance, ByVal XmlIn() As Byte)
            MyBase.New
            Me.OperatorCode = OperatorCode
            Me.OperatorPassword = OperatorPassword
            Me.CompanyId = CompanyId
            Me.CompanyPassword = CompanyPassword
            Me.LanguageCode = LanguageCode
            Me.LogLevel = LogLevel
            Me.EncoreInstance = EncoreInstance
            Me.XmlIn = XmlIn
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Logon_With_ByteArrayResponse", WrapperNamespace:="http://www.syspro.com/ns/utilities/", IsWrapped:=true)>  _
    Partial Public Class Logon_With_ByteArray1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=0)>  _
        Public Logon_With_ByteArrayResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Logon_With_ByteArrayResult As String)
            MyBase.New
            Me.Logon_With_ByteArrayResult = Logon_With_ByteArrayResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LogoffRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Logoff", [Namespace]:="http://www.syspro.com/ns/utilities/", Order:=0)>  _
        Public Body As SysproUtilitiesService.LogoffRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SysproUtilitiesService.LogoffRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.syspro.com/ns/utilities/")>  _
    Partial Public Class LogoffRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UserId As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String)
            MyBase.New
            Me.UserId = UserId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LogoffResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LogoffResponse", [Namespace]:="http://www.syspro.com/ns/utilities/", Order:=0)>  _
        Public Body As SysproUtilitiesService.LogoffResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As SysproUtilitiesService.LogoffResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.syspro.com/ns/utilities/")>  _
    Partial Public Class LogoffResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public LogoffResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LogoffResult As String)
            MyBase.New
            Me.LogoffResult = LogoffResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetLogonProfile_With_String", WrapperNamespace:="http://www.syspro.com/ns/utilities/", IsWrapped:=true)>  _
    Partial Public Class GetLogonProfile_With_String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=0)>  _
        Public UserId As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String)
            MyBase.New
            Me.UserId = UserId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetLogonProfile_With_StringResponse", WrapperNamespace:="http://www.syspro.com/ns/utilities/", IsWrapped:=true)>  _
    Partial Public Class GetLogonProfile_With_String1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=0)>  _
        Public GetLogonProfile_With_StringResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetLogonProfile_With_StringResult As String)
            MyBase.New
            Me.GetLogonProfile_With_StringResult = GetLogonProfile_With_StringResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetLogonProfile_With_ByteArray", WrapperNamespace:="http://www.syspro.com/ns/utilities/", IsWrapped:=true)>  _
    Partial Public Class GetLogonProfile_With_ByteArray
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=0)>  _
        Public UserId As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String)
            MyBase.New
            Me.UserId = UserId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetLogonProfile_With_ByteArrayResponse", WrapperNamespace:="http://www.syspro.com/ns/utilities/", IsWrapped:=true)>  _
    Partial Public Class GetLogonProfile_With_ByteArray1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=0)>  _
        Public GetLogonProfile_With_ByteArrayResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetLogonProfile_With_ByteArrayResult() As Byte)
            MyBase.New
            Me.GetLogonProfile_With_ByteArrayResult = GetLogonProfile_With_ByteArrayResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Run_With_String", WrapperNamespace:="http://www.syspro.com/ns/utilities/", IsWrapped:=true)>  _
    Partial Public Class Run_With_String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=0)>  _
        Public UserId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=1)>  _
        Public BusinessObject As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=2)>  _
        Public Parameter As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserId As String, ByVal BusinessObject As String, ByVal Parameter As String)
            MyBase.New
            Me.UserId = UserId
            Me.BusinessObject = BusinessObject
            Me.Parameter = Parameter
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Run_With_StringResponse", WrapperNamespace:="http://www.syspro.com/ns/utilities/", IsWrapped:=true)>  _
    Partial Public Class Run_With_String1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://www.syspro.com/ns/utilities/", Order:=0)>  _
        Public Run_With_StringResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Run_With_StringResult As String)
            MyBase.New
            Me.Run_With_StringResult = Run_With_StringResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface utilitiesclassSoapChannel
        Inherits SysproUtilitiesService.utilitiesclassSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class utilitiesclassSoapClient
        Inherits System.ServiceModel.ClientBase(Of SysproUtilitiesService.utilitiesclassSoap)
        Implements SysproUtilitiesService.utilitiesclassSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproUtilitiesService_utilitiesclassSoap_Logon(ByVal request As SysproUtilitiesService.Logon_With_String) As SysproUtilitiesService.Logon_With_String1 Implements SysproUtilitiesService.utilitiesclassSoap.Logon
            Return MyBase.Channel.Logon(request)
        End Function
        
        Public Function Logon(ByVal OperatorCode As String, ByVal OperatorPassword As String, ByVal CompanyId As String, ByVal CompanyPassword As String, ByVal LanguageCode As SysproUtilitiesService.Language, ByVal LogLevel As SysproUtilitiesService.LogDetail, ByVal EncoreInstance As SysproUtilitiesService.Instance, ByVal XmlIn As String) As String
            Dim inValue As SysproUtilitiesService.Logon_With_String = New SysproUtilitiesService.Logon_With_String()
            inValue.OperatorCode = OperatorCode
            inValue.OperatorPassword = OperatorPassword
            inValue.CompanyId = CompanyId
            inValue.CompanyPassword = CompanyPassword
            inValue.LanguageCode = LanguageCode
            inValue.LogLevel = LogLevel
            inValue.EncoreInstance = EncoreInstance
            inValue.XmlIn = XmlIn
            Dim retVal As SysproUtilitiesService.Logon_With_String1 = CType(Me,SysproUtilitiesService.utilitiesclassSoap).Logon(inValue)
            Return retVal.Logon_With_StringResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproUtilitiesService_utilitiesclassSoap_LogonAsync(ByVal request As SysproUtilitiesService.Logon_With_String) As System.Threading.Tasks.Task(Of SysproUtilitiesService.Logon_With_String1) Implements SysproUtilitiesService.utilitiesclassSoap.LogonAsync
            Return MyBase.Channel.LogonAsync(request)
        End Function
        
        Public Function LogonAsync(ByVal OperatorCode As String, ByVal OperatorPassword As String, ByVal CompanyId As String, ByVal CompanyPassword As String, ByVal LanguageCode As SysproUtilitiesService.Language, ByVal LogLevel As SysproUtilitiesService.LogDetail, ByVal EncoreInstance As SysproUtilitiesService.Instance, ByVal XmlIn As String) As System.Threading.Tasks.Task(Of SysproUtilitiesService.Logon_With_String1)
            Dim inValue As SysproUtilitiesService.Logon_With_String = New SysproUtilitiesService.Logon_With_String()
            inValue.OperatorCode = OperatorCode
            inValue.OperatorPassword = OperatorPassword
            inValue.CompanyId = CompanyId
            inValue.CompanyPassword = CompanyPassword
            inValue.LanguageCode = LanguageCode
            inValue.LogLevel = LogLevel
            inValue.EncoreInstance = EncoreInstance
            inValue.XmlIn = XmlIn
            Return CType(Me,SysproUtilitiesService.utilitiesclassSoap).LogonAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproUtilitiesService_utilitiesclassSoap_LogonW(ByVal request As SysproUtilitiesService.Logon_With_ByteArray) As SysproUtilitiesService.Logon_With_ByteArray1 Implements SysproUtilitiesService.utilitiesclassSoap.LogonW
            Return MyBase.Channel.LogonW(request)
        End Function
        
        Public Function LogonW(ByVal OperatorCode As String, ByVal OperatorPassword As String, ByVal CompanyId As String, ByVal CompanyPassword As String, ByVal LanguageCode As SysproUtilitiesService.Language, ByVal LogLevel As SysproUtilitiesService.LogDetail, ByVal EncoreInstance As SysproUtilitiesService.Instance, ByVal XmlIn() As Byte) As String
            Dim inValue As SysproUtilitiesService.Logon_With_ByteArray = New SysproUtilitiesService.Logon_With_ByteArray()
            inValue.OperatorCode = OperatorCode
            inValue.OperatorPassword = OperatorPassword
            inValue.CompanyId = CompanyId
            inValue.CompanyPassword = CompanyPassword
            inValue.LanguageCode = LanguageCode
            inValue.LogLevel = LogLevel
            inValue.EncoreInstance = EncoreInstance
            inValue.XmlIn = XmlIn
            Dim retVal As SysproUtilitiesService.Logon_With_ByteArray1 = CType(Me,SysproUtilitiesService.utilitiesclassSoap).LogonW(inValue)
            Return retVal.Logon_With_ByteArrayResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproUtilitiesService_utilitiesclassSoap_LogonWAsync(ByVal request As SysproUtilitiesService.Logon_With_ByteArray) As System.Threading.Tasks.Task(Of SysproUtilitiesService.Logon_With_ByteArray1) Implements SysproUtilitiesService.utilitiesclassSoap.LogonWAsync
            Return MyBase.Channel.LogonWAsync(request)
        End Function
        
        Public Function LogonWAsync(ByVal OperatorCode As String, ByVal OperatorPassword As String, ByVal CompanyId As String, ByVal CompanyPassword As String, ByVal LanguageCode As SysproUtilitiesService.Language, ByVal LogLevel As SysproUtilitiesService.LogDetail, ByVal EncoreInstance As SysproUtilitiesService.Instance, ByVal XmlIn() As Byte) As System.Threading.Tasks.Task(Of SysproUtilitiesService.Logon_With_ByteArray1)
            Dim inValue As SysproUtilitiesService.Logon_With_ByteArray = New SysproUtilitiesService.Logon_With_ByteArray()
            inValue.OperatorCode = OperatorCode
            inValue.OperatorPassword = OperatorPassword
            inValue.CompanyId = CompanyId
            inValue.CompanyPassword = CompanyPassword
            inValue.LanguageCode = LanguageCode
            inValue.LogLevel = LogLevel
            inValue.EncoreInstance = EncoreInstance
            inValue.XmlIn = XmlIn
            Return CType(Me,SysproUtilitiesService.utilitiesclassSoap).LogonWAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproUtilitiesService_utilitiesclassSoap_Logoff(ByVal request As SysproUtilitiesService.LogoffRequest) As SysproUtilitiesService.LogoffResponse Implements SysproUtilitiesService.utilitiesclassSoap.Logoff
            Return MyBase.Channel.Logoff(request)
        End Function
        
        Public Function Logoff(ByVal UserId As String) As String
            Dim inValue As SysproUtilitiesService.LogoffRequest = New SysproUtilitiesService.LogoffRequest()
            inValue.Body = New SysproUtilitiesService.LogoffRequestBody()
            inValue.Body.UserId = UserId
            Dim retVal As SysproUtilitiesService.LogoffResponse = CType(Me,SysproUtilitiesService.utilitiesclassSoap).Logoff(inValue)
            Return retVal.Body.LogoffResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproUtilitiesService_utilitiesclassSoap_LogoffAsync(ByVal request As SysproUtilitiesService.LogoffRequest) As System.Threading.Tasks.Task(Of SysproUtilitiesService.LogoffResponse) Implements SysproUtilitiesService.utilitiesclassSoap.LogoffAsync
            Return MyBase.Channel.LogoffAsync(request)
        End Function
        
        Public Function LogoffAsync(ByVal UserId As String) As System.Threading.Tasks.Task(Of SysproUtilitiesService.LogoffResponse)
            Dim inValue As SysproUtilitiesService.LogoffRequest = New SysproUtilitiesService.LogoffRequest()
            inValue.Body = New SysproUtilitiesService.LogoffRequestBody()
            inValue.Body.UserId = UserId
            Return CType(Me,SysproUtilitiesService.utilitiesclassSoap).LogoffAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproUtilitiesService_utilitiesclassSoap_GetLogonProfile(ByVal request As SysproUtilitiesService.GetLogonProfile_With_String) As SysproUtilitiesService.GetLogonProfile_With_String1 Implements SysproUtilitiesService.utilitiesclassSoap.GetLogonProfile
            Return MyBase.Channel.GetLogonProfile(request)
        End Function
        
        Public Function GetLogonProfile(ByVal UserId As String) As String
            Dim inValue As SysproUtilitiesService.GetLogonProfile_With_String = New SysproUtilitiesService.GetLogonProfile_With_String()
            inValue.UserId = UserId
            Dim retVal As SysproUtilitiesService.GetLogonProfile_With_String1 = CType(Me,SysproUtilitiesService.utilitiesclassSoap).GetLogonProfile(inValue)
            Return retVal.GetLogonProfile_With_StringResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproUtilitiesService_utilitiesclassSoap_GetLogonProfileAsync(ByVal request As SysproUtilitiesService.GetLogonProfile_With_String) As System.Threading.Tasks.Task(Of SysproUtilitiesService.GetLogonProfile_With_String1) Implements SysproUtilitiesService.utilitiesclassSoap.GetLogonProfileAsync
            Return MyBase.Channel.GetLogonProfileAsync(request)
        End Function
        
        Public Function GetLogonProfileAsync(ByVal UserId As String) As System.Threading.Tasks.Task(Of SysproUtilitiesService.GetLogonProfile_With_String1)
            Dim inValue As SysproUtilitiesService.GetLogonProfile_With_String = New SysproUtilitiesService.GetLogonProfile_With_String()
            inValue.UserId = UserId
            Return CType(Me,SysproUtilitiesService.utilitiesclassSoap).GetLogonProfileAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproUtilitiesService_utilitiesclassSoap_GetLogonProfileW(ByVal request As SysproUtilitiesService.GetLogonProfile_With_ByteArray) As SysproUtilitiesService.GetLogonProfile_With_ByteArray1 Implements SysproUtilitiesService.utilitiesclassSoap.GetLogonProfileW
            Return MyBase.Channel.GetLogonProfileW(request)
        End Function
        
        Public Function GetLogonProfileW(ByVal UserId As String) As Byte()
            Dim inValue As SysproUtilitiesService.GetLogonProfile_With_ByteArray = New SysproUtilitiesService.GetLogonProfile_With_ByteArray()
            inValue.UserId = UserId
            Dim retVal As SysproUtilitiesService.GetLogonProfile_With_ByteArray1 = CType(Me,SysproUtilitiesService.utilitiesclassSoap).GetLogonProfileW(inValue)
            Return retVal.GetLogonProfile_With_ByteArrayResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproUtilitiesService_utilitiesclassSoap_GetLogonProfileWAsync(ByVal request As SysproUtilitiesService.GetLogonProfile_With_ByteArray) As System.Threading.Tasks.Task(Of SysproUtilitiesService.GetLogonProfile_With_ByteArray1) Implements SysproUtilitiesService.utilitiesclassSoap.GetLogonProfileWAsync
            Return MyBase.Channel.GetLogonProfileWAsync(request)
        End Function
        
        Public Function GetLogonProfileWAsync(ByVal UserId As String) As System.Threading.Tasks.Task(Of SysproUtilitiesService.GetLogonProfile_With_ByteArray1)
            Dim inValue As SysproUtilitiesService.GetLogonProfile_With_ByteArray = New SysproUtilitiesService.GetLogonProfile_With_ByteArray()
            inValue.UserId = UserId
            Return CType(Me,SysproUtilitiesService.utilitiesclassSoap).GetLogonProfileWAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproUtilitiesService_utilitiesclassSoap_Run(ByVal request As SysproUtilitiesService.Run_With_String) As SysproUtilitiesService.Run_With_String1 Implements SysproUtilitiesService.utilitiesclassSoap.Run
            Return MyBase.Channel.Run(request)
        End Function
        
        Public Function Run(ByVal UserId As String, ByVal BusinessObject As String, ByVal Parameter As String) As String
            Dim inValue As SysproUtilitiesService.Run_With_String = New SysproUtilitiesService.Run_With_String()
            inValue.UserId = UserId
            inValue.BusinessObject = BusinessObject
            inValue.Parameter = Parameter
            Dim retVal As SysproUtilitiesService.Run_With_String1 = CType(Me,SysproUtilitiesService.utilitiesclassSoap).Run(inValue)
            Return retVal.Run_With_StringResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SysproUtilitiesService_utilitiesclassSoap_RunAsync(ByVal request As SysproUtilitiesService.Run_With_String) As System.Threading.Tasks.Task(Of SysproUtilitiesService.Run_With_String1) Implements SysproUtilitiesService.utilitiesclassSoap.RunAsync
            Return MyBase.Channel.RunAsync(request)
        End Function
        
        Public Function RunAsync(ByVal UserId As String, ByVal BusinessObject As String, ByVal Parameter As String) As System.Threading.Tasks.Task(Of SysproUtilitiesService.Run_With_String1)
            Dim inValue As SysproUtilitiesService.Run_With_String = New SysproUtilitiesService.Run_With_String()
            inValue.UserId = UserId
            inValue.BusinessObject = BusinessObject
            inValue.Parameter = Parameter
            Return CType(Me,SysproUtilitiesService.utilitiesclassSoap).RunAsync(inValue)
        End Function
    End Class
End Namespace
