'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Log
    Public Property ID As Integer
    Public Property LogType As Nullable(Of LogType)
    Public Property Reference As String
    Public Property XmlIn As String
    Public Property XmlParam As String
    Public Property XmlOut As String
    Public Property Successful As Nullable(Of Boolean)
    Public Property TrnTime As String
    Public Property TrnUser As String
    Public Property HostName As String
    Public Property IPAddress As String
    Public Property WindowsUser As String
    Public Property BusinessObject As String
    Public Property ValidateOnly As Nullable(Of Boolean)
    Public Property DocumentNumber As String
    Public Property IsException As Nullable(Of Boolean)
    Public Property Note As String

End Class
