'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Public Enum LogType As Integer
    SOCreate = 0
    SOCancel = 1
    SOStatusChange = 2
    SOMoveQty = 3
    POCreate = 10
    POAddLine = 11
    PODeleteLine = 12
    POMaintainLine = 13
    GRNCreate = 20
    InvoiceCreate = 30
    POCancel = 14
    PONegReceipt = 15
    ArInvoice = 4
End Enum
